-- Generated by Noctalia

local primary = "rgb(e6a6c8)"
local surface = "rgb(10111b)"
local on_surface = "rgb(eee7f0)"
local secondary = "rgb(afa2d8)"
local on_secondary = "rgb(1d1830)"
local error = "rgb(f08a9b)"
local on_error = "rgb(2d0b14)"
local shadow = "rgb(05060a)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        decoration = {
            shadow = {
                color = shadow,
            },
            glow = {
                color = shadow,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                gradients = true,
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
        shadow = shadow,
    },
    apply_theme = apply_theme
}
