color0 #3f4949
color1 #ffb4ab
color2 #80d4d9
color3 #b1cccd
color4 #b5c7e9
color5 #80d4d9
color6 #b1cccd
color7 #dde4e4
color8 #899393
color9 #ffb4ab
color10 #80d4d9
color11 #b1cccd
color12 #b5c7e9
color13 #80d4d9
color14 #b1cccd
color15 #dde4e4

cursor                #dde4e4
cursor_text_color     #0e1415
background            #0e1415
foreground            #dde4e4
selection_foreground  #bec8c9
selection_background  #3f4949
active_border_color   #80d4d9
inactive_border_color #3f4949
url_color             #80d4d9

active_tab_foreground   #003739
active_tab_background   #80d4d9
inactive_tab_foreground #bec8c9
inactive_tab_background #3f4949
cursor_trail_color      #bec8c9
