color0 #384956
color1 #ffb4ab
color2 #4fdbd1
color3 #81d5ce
color4 #94cdf7
color5 #4fdbd1
color6 #81d5ce
color7 #dbe3ed
color8 #8193a2
color9 #ffb4ab
color10 #4fdbd1
color11 #81d5ce
color12 #94cdf7
color13 #4fdbd1
color14 #81d5ce
color15 #dbe3ed

cursor                #dbe3ed
cursor_text_color     #0c141b
background            #0c141b
foreground            #dbe3ed
selection_foreground  #b7c9d9
selection_background  #384956
active_border_color   #4fdbd1
inactive_border_color #384956
url_color             #4fdbd1

active_tab_foreground   #003734
active_tab_background   #4fdbd1
inactive_tab_foreground #b7c9d9
inactive_tab_background #384956
cursor_trail_color      #b7c9d9
