color0 #000000
color1 #d06666
color2 #53d390
color3 #f0e68c
color4 #519bff
color5 #c28eff
color6 #5abaae
color7 #dddbd5
color8 #666666
color9 #ffa0a0
color10 #96ea7f
color11 #ffa247
color12 #87ceeb
color13 #d2adff
color14 #8fd1c7
color15 #fff9f2

cursor                #f58888
cursor_text_color     #000000
background            #000000
foreground            #f0ebe6
selection_foreground  #f0ebe6
selection_background  #5a3824
active_border_color   #d06666
inactive_border_color #080808
url_color             #d06666

active_tab_foreground   #1a1a1a
active_tab_background   #d06666
inactive_tab_foreground #f0ebe6
inactive_tab_background #080808
cursor_trail_color      #f0ebe6
