color0 #16161c
color1 #e95678
color2 #29d398
color3 #fab795
color4 #26bbd9
color5 #ee64ac
color6 #59e1e3
color7 #d5d8da
color8 #5b5858
color9 #ec6a88
color10 #3fdaa4
color11 #fbc3a7
color12 #3fc4de
color13 #f075b5
color14 #6be4e6
color15 #fdf0ed

cursor                #25b2bc
cursor_text_color     #16161c
background            #1c1e26
foreground            #fdf0ed
selection_foreground  #fdf0ed
selection_background  #2e303e
active_border_color   #25b2bc
inactive_border_color #232530
url_color             #25b2bc

active_tab_foreground   #16161c
active_tab_background   #25b2bc
inactive_tab_foreground #6c6f93
inactive_tab_background #232530
cursor_trail_color      #6c6f93
