color0 #3f4759
color1 #ffb4ab
color2 #54d6f3
color3 #84d2e6
color4 #adc6ff
color5 #54d6f3
color6 #84d2e6
color7 #dfe2ef
color8 #8991a5
color9 #ffb4ab
color10 #54d6f3
color11 #84d2e6
color12 #adc6ff
color13 #54d6f3
color14 #84d2e6
color15 #dfe2ef

cursor                #dfe2ef
cursor_text_color     #0f131c
background            #0f131c
foreground            #dfe2ef
selection_foreground  #bfc6dc
selection_background  #3f4759
active_border_color   #54d6f3
inactive_border_color #3f4759
url_color             #54d6f3

active_tab_foreground   #003640
active_tab_background   #54d6f3
inactive_tab_foreground #bfc6dc
inactive_tab_background #3f4759
cursor_trail_color      #bfc6dc
