# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x291415ff
rootcolor = 0x291415ff
bordercolor = 0x716263ff
dropcolor = 0xe4677080
splitcolor = 0xd6cd5cff
focuscolor = 0xe46770ff
maximizescreencolor = 0xd6905cff
urgentcolor = 0x99272fff
scratchpadcolor = 0xd6cd5cff
globalcolor = 0x8d0c15ff
overlaycolor = 0x6f3910ff
jump_label_decorate_fg_color = 0xf3f2f2ff
jump_label_decorate_bg_color = 0x3e1e20ff
jump_label_decorate_focus_fg_color = 0x251819ff
jump_label_decorate_focus_bg_color = 0xe46770ff
jump_label_decorate_border_color = 0x716263ff
group_bar_decorate_fg_color = 0xf3f2f2ff
group_bar_decorate_bg_color = 0x3e1e20ff
group_bar_decorate_focus_fg_color = 0x251819ff
group_bar_decorate_focus_bg_color = 0xe46770ff
group_bar_decorate_border_color = 0x716263ff
