# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x05060aff
rootcolor = 0x10111bff
bordercolor = 0x645d74ff
dropcolor = 0xe6a6c880
splitcolor = 0x7fb6d6ff
focuscolor = 0xe6a6c8ff
maximizescreencolor = 0xafa2d8ff
urgentcolor = 0xf08a9bff
scratchpadcolor = 0x7fb6d6ff
globalcolor = 0xb12971ff
overlaycolor = 0x4a3295ff
jump_label_decorate_fg_color = 0xeee7f0ff
jump_label_decorate_bg_color = 0x262237ff
jump_label_decorate_focus_fg_color = 0x2b1422ff
jump_label_decorate_focus_bg_color = 0xe6a6c8ff
jump_label_decorate_border_color = 0x645d74ff
group_bar_decorate_fg_color = 0xeee7f0ff
group_bar_decorate_bg_color = 0x262237ff
group_bar_decorate_focus_fg_color = 0x2b1422ff
group_bar_decorate_focus_bg_color = 0xe6a6c8ff
group_bar_decorate_border_color = 0x645d74ff
