# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x1c1c1cff
bordercolor = 0x676767ff
dropcolor = 0x9b1b3080
splitcolor = 0xf0e68cff
focuscolor = 0x9b1b30ff
maximizescreencolor = 0xff6f61ff
urgentcolor = 0xfd1b22ff
scratchpadcolor = 0xf0e68cff
globalcolor = 0x470610ff
overlaycolor = 0xae0f00ff
jump_label_decorate_fg_color = 0xf8f8f2ff
jump_label_decorate_bg_color = 0x474747ff
jump_label_decorate_focus_fg_color = 0xf8f8f2ff
jump_label_decorate_focus_bg_color = 0x9b1b30ff
jump_label_decorate_border_color = 0x676767ff
group_bar_decorate_fg_color = 0xf8f8f2ff
group_bar_decorate_bg_color = 0x474747ff
group_bar_decorate_focus_fg_color = 0xf8f8f2ff
group_bar_decorate_focus_bg_color = 0x9b1b30ff
group_bar_decorate_border_color = 0x676767ff
